info:
  version: 0.0.1
  nodeId: "${HOSTNAME}-onestoplogshop-web"

server:
  servlet:
    session:
      timeout: 1800
spring:
  application:
    name: onestoplogshop
  datasource:
    url: jdbc:h2:file:./onestoplogshop
    driverClassName: org.h2.Driver
    username: sa
    password: password
  #  thymeleaf:
  #    mode: HTML
  #    cache: false
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        format_sql: false
        cache:
          use_second_level_cache: false
  h2:
    console.enabled: false
  web:
    resources:
      static-locations: classpath:/static/
  security:
    oauth2:
      client:
        provider:
          default:
            issuer-uri: ${SSO_ISSUER_URI}
        registration:
          default-sso:
            provider: default
            client-id: ${SSO_CLIENT_ID}
            client-secret: ${SSO_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
  sql:
    init:
      mode: always

listener:
  socket:
    port: 9000

onestoplogshop:
  maintenance:
    max-rows: 100000