version: '3.1'

services:
  client:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./mkfifo-for-accesslog.sh:/docker-entrypoint.d/00-mkfifo-for-accesslog.sh
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
