# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Main checkout
        uses: actions/checkout@v3

      - name: Switch to node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Test with Maven
        run: mvn -Pdevelopment clean install

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/target/surefire-reports/TEST-*.xml"

      # Runs a set of commands using the runners shell
      - name: Set version
        run: |
          mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ env.VERSION }}

      - name: Build release
        run: mvn clean install -Prelease -DskipTest=true

#      - name: Upload release
#        run: cd work && ./deploy.sh ${{ env.VERSION }} release && cd -
